richard:
  datasource:
    default:
      driver: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/purchase
      username: root
      password: 1234
      repository: com.richard.demo.repository
      entity: com.richard.demo.entity