spring:
    application:
        name: demo
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/userinfo
        username: root
        password: 1234